<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-control pwd-in ng-untou_6c5235</name>
   <tag></tag>
   <elementGuidId>ba5f7071-3692-4ad4-b827-80982b5baab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.pwd-in.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cdbf95e-db24-45b7-8282-0609b9041235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2b692e27-3e54-4f2f-b308-bd17b8d9a79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>0672f826-a764-4ea4-91e6-7c216b995c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>296348ac-f69a-48d6-94f0-1d517bcd54d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>password-addon</value>
      <webElementGuid>b780f757-7067-4ecd-850e-a605284751e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pwd-in ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>f92d4e3e-3fdf-4b26-971a-bc009bf24cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b6f12f25-69c9-4aa3-8106-890d4020f582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;remove-overflow&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login_main&quot;]/div[1]/div[@class=&quot;d-flex w-100 overflow-hidden bg-white&quot;]/div[@class=&quot;login-form-sec align-self-center loginformscroll&quot;]/div[@class=&quot;login-right pt-5 my-md-4&quot;]/div[1]/form[@class=&quot;form-horizontal ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;mb-3 ng-star-inserted&quot;]/div[@class=&quot;input-group auth-pass-inputgroup&quot;]/input[@class=&quot;form-control pwd-in ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>b3c0eee8-f624-45bb-85b8-d7649fbb3c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>d699eef6-1894-4da7-8b3e-bd564b3737ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>424d158c-f3fb-4ea0-b17c-d7aed07619e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your password' and @type = 'password']</value>
      <webElementGuid>97583270-30b0-436c-bf78-50e7af996f8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
